### ISSUE TITLE
Confusing error about "dist" folder

### ISSUE THREAD

**Issue by peterbe** [mozilla/acidity#22]
```
peterbe@mpb:~$ acidity airmozilla
"dist" folder does not exist!
No LICENSE found! :-(
No README found! :-(
You have 19 files in the root directory:
maybe you can try moving your files into folders?

Tests failed: 3/3
peterbe@mpb:~$ ls airmozilla/LICENSE
airmozilla/LICENSE
peterbe@mpb:~$ ls airmozilla/README.md
airmozilla/README.md
```

What does the `"dist" folder does not exist!` mean? I guess, the issue here is that that message isn't clear. 

Also, note that it failed to pick up that my project has a LICENSE file and a README.md file.

**Comment by tofumatt** [comment]
You'll need to use the `--dir=airmozilla` option currently, though you make a good point that with no other args maybe specifying the directory would be neat.

The library currently tests node.js-style libs, so I'm not sure how well it'll do for a Python/PHP project... which I think Air Mozilla is, right?
